import React, { useEffect, useState } from "react";
import { Square, Zap, Wifi } from "lucide-react";
import { api, send } from "../../services/api";
import type { InternetHealth, Status, User } from "../../types";
import { Header, PanelTitle, Empty, Metric, Legend, canEdit, hasPermission } from "../../components/Common";

type Resources = { current: { cpu_percent:number; process_cpu_percent:number; ram_percent:number; process_rss_bytes:number; disk_percent:number; disk_free_bytes:number; process_threads:number }; history: Array<{timestamp:string;cpu_percent:number;ram_percent:number}> };
const mb=(n:number)=>`${(n/1024/1024).toFixed(1)} MB`; const gb=(n:number)=>`${(n/1024/1024/1024).toFixed(1)} GB`;
function Sparkline({values}:{values:number[]}) { const w=420,h=90,max=Math.max(...values,1),min=Math.min(...values,0); const points=values.map((v,i)=>`${(i/Math.max(values.length-1,1))*w},${h-((v-min)/Math.max(max-min,1))*h}`).join(" "); return <svg className="metric-chart" viewBox={`0 0 ${w} ${h}`} role="img"><polyline fill="none" points={points}/></svg>; }

export function Dashboard({ user }: { user: User }) {
    const [data,setData]=useState<Status|null>(null), [internet,setInternet]=useState<InternetHealth|null>(null), [resources,setResources]=useState<Resources|null>(null), [publication,setPublication]=useState("NONE");
    const canViewLogs=hasPermission(user,"logs","view"), canViewSync=hasPermission(user,"sync","view");
    const load=()=>api<Status>("/api/status").then(setData).catch(()=>undefined);
    useEffect(()=>{load();const t=setInterval(load,3000);return()=>clearInterval(t)},[]);
    useEffect(()=>{const a=()=>api<InternetHealth>("/api/v1/internet-health").then(setInternet).catch(()=>setInternet(null));const b=()=>api<Resources>("/api/v1/resources").then(setResources).catch(()=>setResources(null));a();b();const t=setInterval(()=>{a();b()},3000);return()=>clearInterval(t)},[]);
    const total=data?.total_canais||0,online=data?.canais_online||0,offline=data?.canais_offline||0,unknown=data?.canais_desconhecidos||Math.max(total-online-offline,0),rate=total&&online+offline?Math.round(online/total*100):null,running=data?.status==="Executando..."||data?.status==="Pausado";
    const start=()=>send("/api/v1/sync",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({publication_mode:publication})}).then(load).catch(()=>undefined);
    return <><Header kicker="MONITORAMENTO AO VIVO" title="Painel geral" description="Recursos do servidor, conectividade, canais e execução em tempo real.">{canEdit(user)&&<div className="actions"><select className="button subtle" value={publication} onChange={e=>setPublication(e.target.value)} disabled={running}><option value="NONE">Não publicar links</option><option value="CREATE">Criar links novos</option><option value="UPDATE">Atualizar links existentes</option><option value="CREATE_UPDATE">Criar + atualizar</option></select><button className="button primary" disabled={running} onClick={start}><Zap size={15}/> Iniciar sincronização</button><button className="button subtle" disabled={!running} onClick={()=>send("/api/v1/sync/pause").then(load)}>{data?.status==="Pausado"?"Retomar":"Pausar"}</button><button className="button danger" disabled={!running} onClick={()=>confirm("Interromper a execução atual?")&&send("/api/v1/sync/stop").then(load)}><Square size={14}/> Interromper</button></div>}</Header>
    <section className="resource-metric-grid"><Metric label="CPU" value={`${resources?.current.cpu_percent??0}%`} detail={`${resources?.current.process_cpu_percent??0}% processo`} tone="blue"/><Metric label="RAM" value={`${resources?.current.ram_percent??0}%`} detail={mb(resources?.current.process_rss_bytes??0)+" processo"} tone="green"/><Metric label="Disco" value={`${resources?.current.disk_percent??0}%`} detail={`${gb(resources?.current.disk_free_bytes??0)} livres`} tone="blue"/><Metric label="Threads" value={resources?.current.process_threads??0} detail="processo atual" tone="blue"/></section>
    <section className="resource-chart-grid"><div className="panel"><PanelTitle kicker="RECURSOS" title="CPU — histórico" badge="AO VIVO"/><Sparkline values={(resources?.history||[]).map(x=>x.cpu_percent)}/></div><div className="panel"><PanelTitle kicker="RECURSOS" title="RAM — histórico" badge="AO VIVO"/><Sparkline values={(resources?.history||[]).map(x=>x.ram_percent)}/></div></section>
    <section className="metric-grid"><Metric label="Status do processo" value={data?.status||"Carregando"} detail={canViewLogs?(data?.ultimo_log||"Aguardando dados"):"estado operacional"} tone="blue"/><Metric label="Canais catalogados" value={total} detail="base atual" tone="blue"/><Metric label="Online" value={online} detail={rate===null?"verificando":`${rate}% da base`} tone="green"/><Metric label="Offline / removidos" value={offline} detail="última verificação" tone="red"/></section>
    <section className="panel internet-status-panel"><PanelTitle kicker="CONECTIVIDADE" title="Internet" badge="TESTE AUTOMÁTICO"/><div className="internet-status-content"><div className={`internet-status ${internet?.online?"online":internet?"offline":"unknown"}`}><i className="internet-status-dot"/><strong>{internet?.online?"ONLINE":internet?"OFFLINE":"VERIFICANDO"}</strong></div><div className="internet-ping"><Wifi size={16}/><span>Ping</span><b>{internet?`${internet.latency_ms} ms`:"—"}</b></div></div></section>
    <section className="split-grid"><div className="panel health-panel"><PanelTitle kicker="DISTRIBUIÇÃO" title="Saúde dos canais" badge="AO VIVO"/><div className="health-content"><div className="donut" style={{"--progress":`${(rate||0)*3.6}deg`} as React.CSSProperties}><strong>{rate===null?"...":`${rate}%`}</strong><small>{rate===null?"verificando":"online"}</small></div><div className="legend"><Legend label="Online" value={online} color="green"/><Legend label="Offline" value={offline} color="red"/><Legend label="Não verificado" value={unknown} color="muted"/></div></div></div>{canViewLogs&&<div className="panel"><PanelTitle kicker="ATIVIDADE" title="O que está acontecendo" badge={`${data?.log_count||0} eventos`}/><div className="activity-list">{data?.logs?.slice(0,12).map(l=><div className={`activity ${l.level}`} key={`${l.timestamp}-${l.message}`}><time>{l.timestamp.slice(11)}</time><span>{l.message}</span></div>)||<Empty text="Nenhuma atividade registrada."/>}</div></div>}</section>
    {canViewSync&&<div className="panel"><PanelTitle kicker="PIPELINE" title="Progresso da operação" badge={data?.status||"Ocioso"}/><div className="progress-track"><span style={{width:data?.status==="Concluido"?"100%":running?"62%":"12%"}}/></div><div className="progress-labels"><span>Leitura</span><span>Verificação</span><span>Particionamento</span><span>Concluído</span></div></div>}</>;
}
