import React, { useEffect, useMemo, useState } from "react";
import { CheckSquare, ImagePlus, Save, ShieldCheck, UserPlus, UserRound, X } from "lucide-react";
import { api, send } from "../../services/api";
import type { PermissionAction, PermissionMap, User } from "../../types";
import { Header, PanelTitle, Modal, hasPermission } from "../../components/Common";

const ACTIONS: {key:PermissionAction;label:string}[]=[{key:"view",label:"Visualizar"},{key:"create",label:"Criar"},{key:"edit",label:"Editar"},{key:"delete",label:"Excluir"},{key:"execute",label:"Executar"},{key:"admin",label:"Administrar"}];
type ResourceKey=keyof PermissionMap;
type ResourceEntry=readonly [ResourceKey,string];
type PermissionGroup={label:string;resources:readonly ResourceEntry[]};
const GROUPS:readonly PermissionGroup[]=[
 {label:"Operação",resources:[["dashboard","Painel geral"],["channels","Canais"],["playlists","Playlists"],["epg","EPG/XMLTV"]]},
 {label:"Processamento",resources:[["sync","Sincronização"],["health","Monitoramento"]]},
 {label:"Administração",resources:[["settings","Configurações"],["users","Usuários"],["logs","Logs"],["maintenance","Manutenção"],["public_files","Arquivos públicos"],["system","Sistema"]]},
];
type Form={username:string;password:string;role:User["role"];display_name:string;full_name:string;email:string;avatar:string;phone:string;description:string;department:string;active:boolean;expires_at:string;permissions:PermissionMap};
const empty=():Form=>({username:"",password:"",role:"viewer",display_name:"",full_name:"",email:"",avatar:"",phone:"",description:"",department:"",active:true,expires_at:"",permissions:{}});
const rolePermissions=(role:User["role"]):PermissionMap=>{
 if(role==="admin"){
  const resources:ResourceKey[]=GROUPS.flatMap(g=>g.resources.map(([resource])=>resource));
  return Object.fromEntries(resources.map(resource=>[resource,ACTIONS.map(a=>a.key)])) as PermissionMap;
 }
 if(role==="editor")return {dashboard:["view"],channels:["view","create","edit"],playlists:["view","create","edit"],epg:["view","create","edit"],sync:["view","execute"],health:["view"]};
 return {dashboard:["view"],channels:["view"],playlists:["view"],epg:["view"],health:["view"]};
};
const presets:{key:string;label:string;role:User["role"];description:string;permissions?:PermissionMap}[]=[
 {key:"viewer",label:"Consulta",role:"viewer",description:"Somente consulta e acompanhamento."},
 {key:"operator",label:"Operador",role:"editor",description:"Canais, playlists e execução operacional."},
 {key:"monitor",label:"Monitoramento",role:"viewer",description:"Acompanhamento de canais e saúde." ,permissions:{dashboard:["view"],channels:["view"],health:["view"],playlists:["view"]}},
 {key:"publisher",label:"Publicador",role:"editor",description:"Operação e publicação de listas." ,permissions:{dashboard:["view"],channels:["view","create","edit"],playlists:["view","create","edit"],epg:["view","create","edit"],sync:["view","execute"]}},
 {key:"admin",label:"Administrador",role:"admin",description:"Administração completa do sistema."},
];

export function UsersPage({user}:{user:User}){
 const canCreate=hasPermission(user,"users","create"),canEdit=hasPermission(user,"users","edit"),canAdmin=hasPermission(user,"users","admin");
 const [users,setUsers]=useState<User[]>([]),[editing,setEditing]=useState<User|null>(null),[form,setForm]=useState<Form>(empty()),[open,setOpen]=useState(false);
 const load=()=>api<User[]>("/api/v1/users").then(setUsers).catch(()=>undefined); useEffect(()=>{load()},[]);
 const openCreate=()=>{setEditing(null);setForm(empty());setOpen(true)};
 const openEdit=(u:User)=>{setEditing(u);setForm({username:u.username,password:"",role:u.role,display_name:u.display_name||u.username,full_name:u.full_name||"",email:u.email||"",avatar:u.avatar||"",phone:u.phone||"",description:u.description||"",department:u.department||"",active:u.active!==false&&u.active!==0,expires_at:u.expires_at||"",permissions:u.permissions||rolePermissions(u.role)});setOpen(true)};
 const setField=<K extends keyof Form>(k:K,v:Form[K])=>setForm(x=>({...x,[k]:v}));
 const applyPreset=(key:string)=>{const p=presets.find(x=>x.key===key)!;setForm(x=>({...x,role:p.role,permissions:p.permissions||rolePermissions(p.role)}))};
 const toggle=(r:ResourceKey,a:PermissionAction)=>{if(!canAdmin)return;setForm(x=>{const s=new Set(x.permissions[r]||[]);s.has(a)?s.delete(a):s.add(a);return {...x,permissions:{...x.permissions,[r]:[...s]}}})};
 const setGroup=(resources:readonly ResourceEntry[],checked:boolean)=>{if(!canAdmin)return;setForm(x=>{const p={...x.permissions};resources.forEach(([r])=>{p[r]=checked?ACTIONS.map(a=>a.key):[]});return {...x,permissions:p}})};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!form.username.trim()||(!editing&&form.password.length<8)){alert("Informe o login e uma senha de pelo menos 8 caracteres.");return}const payload:Record<string,unknown>={username:form.username.trim(),role:canAdmin?form.role:"viewer",display_name:form.display_name.trim()||form.username.trim(),full_name:form.full_name.trim(),email:form.email.trim(),avatar:form.avatar.trim(),phone:form.phone.trim(),description:form.description.trim(),department:form.department.trim(),active:form.active,expires_at:form.expires_at||null};if(canAdmin)payload.permissions=form.permissions;if(form.password)payload.password=form.password;try{if(editing)await api(`/api/v1/users/${editing.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});else await send("/api/v1/users",{...payload,password:form.password});setOpen(false);setEditing(null);load()}catch{alert("Não foi possível salvar o usuário.")}};
 const title=editing?`Editar usuário: ${editing.username}`:"Criar novo usuário";
 return <><Header kicker="CONTROLE DE ACESSO" title="Usuários" description="Contas, perfis e permissões organizadas por seção." >{canCreate&&<button className="button primary" onClick={openCreate}><UserPlus size={15}/>Novo usuário</button>}</Header><div className="panel"><PanelTitle kicker="CONTAS" title="Usuários cadastrados" badge={`${users.length} conta(s)`}/><div className="table-scroll"><table><thead><tr><th>Usuário</th><th>Nome</th><th>Perfil</th><th>Status</th><th>Criação</th>{canEdit&&<th>Ação</th>}</tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.username}</b></td><td>{u.display_name||"-"}</td><td><span className="tag">{u.role}</span></td><td>{u.active===false||u.active===0?"Inativo":"Ativo"}</td><td>{u.created_at||"-"}</td>{canEdit&&<td><button className="text-button" onClick={()=>openEdit(u)}><UserRound size={14}/>Editar</button></td>}</tr>)}</tbody></table></div></div>{open&&<Modal title={title} close={()=>setOpen(false)}><form className="user-modal-form" onSubmit={save}>
 <section className="form-section"><h3>Identidade e acesso</h3><div className="form-grid"><label>Login *<input required value={form.username} onChange={e=>setField("username",e.target.value)}/></label><label>Nome de exibição *<input required value={form.display_name} onChange={e=>setField("display_name",e.target.value)}/></label><label>Senha {editing?"(opcional)":"*"}<input type="password" minLength={8} required={!editing} value={form.password} onChange={e=>setField("password",e.target.value)} placeholder="Mínimo de 8 caracteres"/></label><label>Status<select value={form.active?"1":"0"} onChange={e=>setField("active",e.target.value==="1")}><option value="1">Ativo</option><option value="0">Inativo</option></select></label></div></section>
 <section className="form-section"><h3>Perfil-base e permissões predefinidas</h3><div className="preset-grid">{presets.filter(p=>canAdmin||p.key!=="admin").map(p=><button type="button" key={p.key} className={`preset ${form.role===p.role&&JSON.stringify(form.permissions)===JSON.stringify(p.permissions||rolePermissions(p.role))?"selected":""}`} onClick={()=>applyPreset(p.key)}><b>{p.label}</b><small>{p.description}</small></button>)}</div><div className="form-grid"><label>Perfil-base *<select disabled={!canAdmin} value={form.role} onChange={e=>{const role=e.target.value as User["role"];setForm(x=>({...x,role,permissions:rolePermissions(role)}))}}><option value="viewer">Viewer</option><option value="editor">Editor</option><option value="admin">Admin</option></select></label><div className="form-help"><ShieldCheck size={15}/><span>Ao escolher um perfil, as permissões correspondentes são preenchidas automaticamente. Você pode ajustar uma a uma abaixo.</span></div></div></section>
 <section className="form-section"><h3>Dados pessoais e organização</h3><div className="form-grid"><label>Nome completo<input value={form.full_name} onChange={e=>setField("full_name",e.target.value)}/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setField("email",e.target.value)}/></label><label>Telefone<input value={form.phone} onChange={e=>setField("phone",e.target.value)}/></label><label>Departamento/grupo<input value={form.department} onChange={e=>setField("department",e.target.value)}/></label><label>Expiração<input type="datetime-local" value={form.expires_at?form.expires_at.slice(0,16):""} onChange={e=>setField("expires_at",e.target.value)}/></label><label>Avatar (URL)<input value={form.avatar} onChange={e=>setField("avatar",e.target.value)} placeholder="https://..."/></label></div><div className="avatar-upload"><ImagePlus size={15}/><span>Avatar do computador</span><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const body=new FormData();body.append("image",f);fetch("/api/v1/users/avatar",{method:"POST",body}).then(r=>r.ok?r.json():Promise.reject()).then(x=>setField("avatar",x.url)).catch(()=>alert("Não foi possível enviar o avatar."))}}/></div><label>Descrição/observação<textarea rows={3} value={form.description} onChange={e=>setField("description",e.target.value)}/></label></section>
 {canAdmin&&<section className="form-section"><div className="section-heading"><h3>Permissões detalhadas</h3><span className="muted-text">Selecione tudo da seção ou personalize por recurso.</span></div>{GROUPS.map(g=><div className="permission-section" key={g.label}><div className="permission-section-head"><b>{g.label}</b><div><button type="button" className="text-button" onClick={()=>setGroup(g.resources,true)}><CheckSquare size={13}/>Selecionar tudo</button><button type="button" className="text-button" onClick={()=>setGroup(g.resources,false)}>Limpar</button></div></div>{g.resources.map(([r,label])=><div className="permission-resource" key={r}><strong>{label}</strong>{ACTIONS.map(a=><label key={a.key}><input type="checkbox" checked={(form.permissions[r]||[]).includes(a.key)} onChange={()=>toggle(r,a.key)}/>{a.label}</label>)}</div>)}</div>)}</section>}
 <div className="modal-actions"><button type="button" className="button subtle" onClick={()=>setOpen(false)}><X size={15}/>Cancelar</button><button className="button primary"><Save size={15}/>{editing?"Salvar alterações":"Criar usuário"}</button></div>
 </form></Modal>}</>;
}
