import React,{createContext,useContext,useEffect,useMemo,useState} from "react";
import {api} from "../services/api";
export type Theme={id:string;name:string;description?:string;bg:string;surface:string;line:string;ink:string;muted:string;accent:string;success:string;danger:string;menu:string;login:string};
export const BUILTIN:Theme[]=[
 {id:"default",name:"M3U Dark",bg:"#071116",surface:"#102128",line:"#263943",ink:"#f4f7f8",muted:"#9baeb4",accent:"#46c3df",success:"#56d6a1",danger:"#f27777",menu:"#10232b",login:"#071116"},
 {id:"light",name:"Claro",bg:"#eef3f5",surface:"#ffffff",line:"#c9d6dc",ink:"#14232d",muted:"#5d7078",accent:"#167e9b",success:"#198b61",danger:"#bd3d4a",menu:"#ffffff",login:"#e8f0f3"},
 {id:"graphite",name:"Grafite",bg:"#101114",surface:"#1a1c21",line:"#343840",ink:"#f2f3f5",muted:"#a1a6b0",accent:"#a8b5ff",success:"#67d6a5",danger:"#ff7e8b",menu:"#20232a",login:"#0c0d10"}
];
type Ctx={themes:Theme[];theme:Theme;setTheme:(id:string)=>void;reload:()=>void};const ThemeContext=createContext<Ctx|null>(null);export const useTheme=()=>useContext(ThemeContext)!;
export function ThemeProvider({userKey,children}:{userKey:string;children:React.ReactNode}){const [themes,setThemes]=useState<Theme[]>(BUILTIN),[id,setId]=useState(localStorage.getItem(`m3u-theme:${userKey}`)||"default");const reload=()=>api<Theme[]>("/api/v1/themes").then(v=>setThemes([...BUILTIN,...v.filter(x=>!BUILTIN.some(b=>b.id===x.id))])).catch(()=>{});useEffect(()=>{reload()},[]);const theme=useMemo(()=>themes.find(t=>t.id===id)||themes[0], [themes,id]);useEffect(()=>{const root=document.documentElement;root.style.setProperty("--theme-bg",theme.bg);root.style.setProperty("--theme-surface",theme.surface);root.style.setProperty("--theme-line",theme.line);root.style.setProperty("--theme-ink",theme.ink);root.style.setProperty("--theme-muted",theme.muted);root.style.setProperty("--theme-accent",theme.accent);root.style.setProperty("--theme-success",theme.success);root.style.setProperty("--theme-danger",theme.danger);root.style.setProperty("--theme-menu",theme.menu);root.style.setProperty("--theme-login",theme.login);root.dataset.theme=theme.id},[theme]);const setTheme=(next:string)=>{setId(next);localStorage.setItem(`m3u-theme:${userKey}`,next)};return <ThemeContext.Provider value={{themes,theme,setTheme,reload}}>{children}</ThemeContext.Provider>}
