import React,{useEffect,useState} from "react";
import {Activity,ChevronRight,Database,Globe,HardDrive,Save,Settings2,Shield,SlidersHorizontal,Timer,Wifi} from "lucide-react";
import {api} from "../../services/api";
import {Header,PanelTitle} from "../../components/Common";

type Config=Record<string,string|number>;
const sections=[
 {id:"execution",label:"Execução",icon:Settings2,desc:"Agendamento, concorrência e processamento."},
 {id:"network",label:"Rede e conectividade",icon:Wifi,desc:"URLs, Internet, EPG e comunicação."},
 {id:"files",label:"Arquivos e cache",icon:HardDrive,desc:"Temporários, imagens e backups."},
 {id:"media",label:"Mídia e tuners",icon:Globe,desc:"xTeVe, EPG, stream e ferramentas."},
 {id:"security",label:"Segurança",icon:Shield,desc:"Autenticação e parâmetros de acesso."},
 {id:"advanced",label:"Avançado",icon:SlidersHorizontal,desc:"Parâmetros menos usados do sistema."},
 {id:"resources",label:"Recursos do servidor",icon:Activity,desc:"CPU, memória, disco, diagnósticos e limites."},
];
const fields:Record<string,{key:string;label:string;type?:string;options?:[string,string][];full?:boolean}[]>={
 execution:[{key:"SCHEDULE_MODE",label:"Modo de automação",options:[["DISABLED","Desativado (manual)"],["INTERVAL","Intervalo regular"],["CRON","Horário fixo diário"]]},{key:"SCHEDULE_INTERVAL_HOURS",label:"Intervalo (horas)"},{key:"SCHEDULE_CRON_TIME",label:"Horário (HH:MM)"},{key:"CONCURRENCY_LIMIT",label:"Concorrência de verificação",type:"number"},{key:"REQUEST_TIMEOUT",label:"Timeout de requisição",type:"number"},{key:"HEALTH_CHECK_INTERVAL_SECONDS",label:"Saúde automática (segundos)",type:"number"}],
 network:[{key:"BASE_URL",label:"URL do menu"},{key:"PUBLIC_BASE_URL",label:"URL dos links públicos"},{key:"WEB_PORT",label:"Porta do menu",type:"number"},{key:"PUBLIC_PORT",label:"Porta dos links",type:"number"},{key:"USER_AGENT",label:"User-Agent"},{key:"REMOTE_M3U_URLS",label:"Links remotos M3U (separados por ;)",full:true},{key:"EPG_URLS",label:"Links EPG XMLTV (separados por ;)",full:true}],
 files:[{key:"MAX_CHANNELS_PER_FILE",label:"Máximo de canais por lista",type:"number"},{key:"TEMP_FILES_LOCATION",label:"Arquivos temporários"},{key:"BACKUP_LOCATION",label:"Local dos backups"},{key:"BACKUPS_TO_KEEP",label:"Backups mantidos",type:"number"},{key:"IMAGE_CACHING",label:"Cache de imagens",options:[["1","Ativado"],["0","Desativado"]]},{key:"REPLACE_MISSING_PROGRAM_IMAGES",label:"Substituir imagens ausentes",options:[["1","Ativado"],["0","Desativado"]]}],
 media:[{key:"AUTO_UPDATE_XTEVE",label:"Atualização automática do xTeVe",options:[["0","Desativada"],["1","Ativada"]]},{key:"NUMBER_OF_TUNERS",label:"Número de tuners",type:"number"},{key:"EPG_SOURCE",label:"Fonte EPG",options:[["PMS","PMS"],["XEPG","XEPG"]]},{key:"STREAM_BUFFER_ENABLED",label:"Buffer de stream",options:[["0","Desativado"],["1","Ativado"]]},{key:"UDPPROXY_ADDRESS",label:"Endereço UDPxy"},{key:"BUFFER_SIZE_MB",label:"Tamanho do buffer (MB)",type:"number"},{key:"CLIENT_CONNECTION_TIMEOUT_MS",label:"Timeout do cliente (ms)",type:"number"},{key:"FFMPEG_BINARY_PATH",label:"Caminho do FFmpeg"},{key:"FFMPEG_OPTIONS",label:"Opções do FFmpeg"},{key:"VLC_BINARY_PATH",label:"Caminho do VLC/CVLC"},{key:"VLC_OPTIONS",label:"Opções do VLC/CVLC"}],
 security:[{key:"WEB_AUTHENTICATION",label:"Autenticação web",options:[["1","Ativada"],["0","Desativada"]]},{key:"API_INTERFACE_ENABLED",label:"Interface API",options:[["1","Ativada"],["0","Desativada"]]},{key:"API_TOKEN",label:"Token da API externa"}],
 advanced:[{key:"FILE_UPDATE_SCHEDULE",label:"Agenda de arquivos"},{key:"UPDATE_FILES_ON_STARTUP",label:"Atualizar arquivos ao iniciar",options:[["0","Não"],["1","Sim"]]}],
};
export function SettingsHubPage(){const [config,setConfig]=useState<Config>({}),[active,setActive]=useState("execution"),[saved,setSaved]=useState(false);useEffect(()=>{api<Config>("/api/config").then(setConfig).catch(()=>{})},[]);const set=(k:string,v:string)=>setConfig(x=>({...x,[k]:v}));const save=()=>api("/api/config",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(config)}).then(()=>{setSaved(true);setTimeout(()=>setSaved(false),2500)});const current=sections.find(x=>x.id===active)!;const Icon=current.icon;return <><Header kicker="SISTEMA" title="Configurações" description="Organize parâmetros por área para localizar e alterar somente o que precisa."/><div className="settings-layout"><aside className="settings-submenu">{sections.map(s=>{const I=s.icon;return <button className={active===s.id?"active":""} onClick={()=>setActive(s.id)} key={s.id}><I size={17}/><span><b>{s.label}</b><small>{s.desc}</small></span><ChevronRight size={14}/></button>})}</aside><section className="panel settings-content"><PanelTitle kicker="CONFIGURAÇÃO" title={current.label} badge={current.id.toUpperCase()}/>{current.id==="resources"?<div className="settings-resource-link"><Activity size={20}/><div><b>Monitoramento de recursos</b><p>CPU, memória RAM, disco, histórico, diagnósticos e limites operacionais.</p></div><a className="button primary" href="/settings/resources">Abrir</a></div>:<><div className="form-grid">{(fields[current.id]||[]).map(f=><label className={f.full?"field-full":""} key={f.key}>{f.label}{f.options?<select value={String(config[f.key]??"")} onChange={e=>set(f.key,e.target.value)}>{f.options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:f.full?<textarea rows={3} value={String(config[f.key]??"")} onChange={e=>set(f.key,e.target.value)}/>:<input type={f.type||"text"} value={String(config[f.key]??"")} onChange={e=>set(f.key,e.target.value)}/>}</label>)}</div>{current.id==="network"&&<div className="settings-test-card"><PanelTitle kicker="CONECTIVIDADE" title="Teste de Internet" badge="TEMPO REAL"/><a className="button subtle" href="/settings/resources"><Wifi size={15}/>Abrir monitoramento e ping</a></div>}<button className="button primary" onClick={save}><Save size={15}/>{saved?"Configurações salvas":"Salvar configurações"}</button></>}</section></div></>}
